### ISSUE TITLE
Dice loss problems

### ISSUE THREAD

**Issue by Lijiaying201812** [YipengHu/label-reg#16]
When I run the program with example downloaded data,I found there was a problem with label_indices =1 and label_indices =2 ,because the dice were almost zero for these condition,What's the reason for the case? Thanks!

**Comment by YipengHu** [comment]
Hi thanks for the question. It is expected in particular during the initial
stages of training. As most of the labels are small (except for Labels #0
which are always the gland segmentation), so they would not have any
overlap before more iterations in. Even when it closes to convergence, some
of them still can be quite small even zeros.

Just FYI: these non-overlap landmarks still generate useful gradients, due
to the multiscale loss, as explained in the paper.
