### ISSUE TITLE
training for larger deformations on 2D Mul-Models datasets

### ISSUE THREAD

**Issue by gaohuiluo** [YipengHu/label-reg#17]
thanks for your open-source code! I'm a first-year graduate students from china.
I'd like to try this approach on 2D Mul-Models datasets(image type is .tif and .jpg), and my label is .mhd/.raw (NDims=3) ,may you give me some advise?

**Comment by YipengHu** [comment]
Hi, Currently, it does not support 2D data. However, I can't see why this
will not be straightforward by changing the conv, pool, resampler, among
other 3D-specific functions, to 2D.

**Comment by RUNLUO** [comment]
Thank you for your prompt reply, I will try this approach and give you feedback.
