### ISSUE TITLE
The detail Running Environment

### ISSUE THREAD

**Issue by NanYoMy** [YipengHu/label-reg#21]
It's a really great job！
I am trying to run my own labeled 3D-image data on the Nvidia 1080GPU.  
And I found the 3D-CNN is really time and memory consuming. could you please tell me the size of 3D-image that you had fed into the neural network. 
Thx

**Comment by YipengHu** [comment]
Yep it can be of a problem. See this: https://github.com/YipengHu/label-reg/wiki/Memory-Constraint
