### ISSUE TITLE
The loss didn't decrease

### ISSUE THREAD

**Issue by yunzhen** [YipengHu/label-reg#24]
I try to use the framework to register fundus images.Because there's very little elastic transformation,I only use the globlenet rather than the composed net.,with vessels as label.However,the loss didn't decrease from the very beginning.

**Comment by YipengHu** [comment]
Thanks for the question, but I need more information help you to diagnose. Can you give me a few examples of these images and labels?

Yipeng
________________________________

**Comment by yunzhen** [comment]
Thank you very much.The attachment is a pair of my labels.
![1_fix](https://user-images.githubusercontent.com/23073809/68121474-d0f2ac80-ff42-11e9-8647-a81884429e39.jpg)
![1_move](https://user-images.githubusercontent.com/23073809/68121482-d3ed9d00-ff42-11e9-8a74-9a083592cf63.jpg)

**Comment by yunzhen** [comment]
the label is not made by hand but predicted by a trained unet model.

**Comment by yunzhen** [comment]
Thank you very much!I  preprocessed the images before sending to the network.Please see the attachment.
![图片1](https://user-images.githubusercontent.com/23073809/68121914-09df5100-ff44-11e9-8d10-0b3b0b8f25c3.png)

**Comment by YipengHu** [comment]
Are they 2D - not sure the code can handle 2D images although the change should be minimal. Also, when you say not decreasing is it diverging or just not changing at all?, the latter probably means some error.

**Comment by yunzhen** [comment]
我重写了网络部分的代码，也修改了多尺度Dice的函数（把3D卷积改成2D，还有修改维度，其它没做改变），来适应二维图像。在网络训练过程中，loss初始为0.5左右，之后一直在0.480~0.50间来回浮动，尝试过调整学习率以及loss的scale，都没有用。

**Comment by YipengHu** [comment]
@yunzhen we have done the same for 2d images and it should work. Your problem should be general debugging/tuning problem. I'd suggest start with simple toy examples first to debug your own code.

**Comment by YipengHu** [comment]
I'm closing this now, but feel free to raise a new one if other specific problems.
