### ISSUE TITLE
Port the tutorial to NiftyNet

### ISSUE THREAD

**Issue by tvercaut** [YipengHu/label-reg#5]
As per https://github.com/NifTK/NiftyNet/issues/212, it would be great for the [README](https://github.com/YipengHu/label-reg/blob/master/README.md) of this repo to be adapted to NiftyNet and placed in the [NiftyNet demo folder](https://github.com/NifTK/NiftyNet/tree/dev/demos)

**Comment by YipengHu** [comment]
we have a new version in tf2 - let's discuss the possibility and close this for now.
